// https://github.com/Bowserinator/Periodic-Table-JSON/blob/master/PeriodicTableJSON.json

export const ELEMENTS = {
    H: {
        name: 'Hydrogen',
        appearance: 'colorless gas',
        atomic_mass: 1.008,
        boil: 20.271,
        category: 'diatomic nonmetal',
        color: null,
        density: 0.08988,
        discovered_by: 'Henry Cavendish',
        melt: 13.99,
        molar_heat: 28.836,
        named_by: 'Antoine Lavoisier',
        number: 1,
        period: 1,
        phase: 'Gas',
        source: 'https://en.wikipedia.org/wiki/Hydrogen',
        spectral_img: 'https://en.wikipedia.org/wiki/File:Hydrogen_Spectra.jpg',
        summary:
            'Hydrogen is a chemical element with chemical symbol H and atomic number 1. With an atomic weight of 1.00794 u, hydrogen is the lightest element on the periodic table. Its monatomic form (H) is the most abundant chemical substance in the Universe, constituting roughly 75% of all baryonic mass.',
        symbol: 'H',
        xpos: 1,
        ypos: 1,
        shells: [1],
        electron_configuration: '1s1',
        electron_affinity: 72.769,
        electronegativity_pauling: 2.2,
        ionization_energies: [1312.0],
    },
    O: {
        name: 'Oxygen',
        appearance: null,
        atomic_mass: 15.999,
        boil: 90.188,
        category: 'diatomic nonmetal',
        color: null,
        density: 1.429,
        discovered_by: 'Carl Wilhelm Scheele',
        melt: 54.36,
        molar_heat: null,
        named_by: 'Antoine Lavoisier',
        number: 8,
        period: 2,
        phase: 'Gas',
        source: 'https://en.wikipedia.org/wiki/Oxygen',
        spectral_img: 'https://en.wikipedia.org/wiki/File:Oxygen_spectre.jpg',
        summary:
            'Oxygen is a chemical element with symbol O and atomic number 8. It is a member of the chalcogen group on the periodic table and is a highly reactive nonmetal and oxidizing agent that readily forms compounds (notably oxides) with most elements. By mass, oxygen is the third-most abundant element in the universe, after hydrogen and helium.',
        symbol: 'O',
        xpos: 16,
        ypos: 2,
        shells: [2, 6],
        electron_configuration: '1s2 2s2 2p4',
        electron_affinity: 140.976,
        electronegativity_pauling: 3.44,
        ionization_energies: [1313.9, 3388.3, 5300.5, 7469.2, 10989.5, 13326.5, 71330, 84078.0],
    },
    C: {
        name: 'Carbon',
        appearance: null,
        atomic_mass: 12.011,
        boil: null,
        category: 'polyatomic nonmetal',
        color: null,
        density: 1.821,
        discovered_by: 'Ancient Egypt',
        melt: null,
        molar_heat: 8.517,
        named_by: null,
        number: 6,
        period: 2,
        phase: 'Solid',
        source: 'https://en.wikipedia.org/wiki/Carbon',
        spectral_img: 'https://en.wikipedia.org/wiki/File:Carbon_Spectra.jpg',
        summary:
            'Carbon (from Latin:carbo "coal") is a chemical element with symbol C and atomic number 6. On the periodic table, it is the first (row 2) of six elements in column (group) 14, which have in common the composition of their outer electron shell. It is nonmetallic and tetravalent\u2014making four electrons available to form covalent chemical bonds.',
        symbol: 'C',
        xpos: 14,
        ypos: 2,
        shells: [2, 4],
        electron_configuration: '1s2 2s2 2p2',
        electron_affinity: 121.7763,
        electronegativity_pauling: 2.55,
        ionization_energies: [1086.5, 2352.6, 4620.5, 6222.7, 37831, 47277.0],
    },
}
